// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredService":       schema_pkg_apis_services_v1alpha1_MonitoredService(ref),
		"github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceSpec":   schema_pkg_apis_services_v1alpha1_MonitoredServiceSpec(ref),
		"github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceStatus": schema_pkg_apis_services_v1alpha1_MonitoredServiceStatus(ref),
	}
}

func schema_pkg_apis_services_v1alpha1_MonitoredService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MonitoredService is the Schema for the monitoredservices API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceSpec", "github.com/GrigoriyMikhalkin/config-monitor/pkg/apis/services/v1alpha1.MonitoredServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_services_v1alpha1_MonitoredServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MonitoredServiceSpec defines the desired state of MonitoredService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_services_v1alpha1_MonitoredServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MonitoredServiceStatus defines the observed state of MonitoredService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
