apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-monitor
  template:
    metadata:
      labels:
        name: config-monitor
    spec:
      serviceAccountName: config-monitor
      containers:
        - name: config-monitor
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - config-monitor
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "config-monitor"
